easy_admin:
  site_name: 'GoFooddy'
  user:
    display_name: true
    display_avatar: true
    name_property_path: 'fullName'
  design:
    menu:
      - { label: "Entities"}
      - label: "Post"
        children:
          - { entity: Post, label: "Posts List", icon: "th-list" }
          - { entity: Post, label: "Add Post", icon: "plus", params: { action: "new" } }
      - label: "Category"
        children:
          - { entity: Category, label: "Category List", icon: "th-list" }
          - { entity: Category, label: "Add Category", icon: "plus", params: { action: "new" } }
      - Tag
      - { label: "Settings" }
      - { entity: User, icon: "user" }
  entities:
    Post:
      class: App\Entity\Post
      label: "Post"
      form:
        fields:
          - { type: 'group', icon: 'pencil', label: 'Basic Information', css_class: 'col-lg-7' }
          - title
          - { property: 'content', type: 'text_editor' }
          - createdAt
          - published
          - { type: 'group', icon: 'th-list', label: 'Other Information', css_class: 'col-lg-5' }
          - category
          - tags
      list:
        collapse_actions: true
        actions: ['show', 'edit', 'delete']
        batch_actions: ['delete']
        title: 'Post List'
        filters: ['title', 'category', 'tags', 'published']
      edit:
        help: 'Hello there'
        fields:
          - '-tags'
    Category:
      class: App\Entity\Category
    Tag:
      class: App\Entity\Tag
    User:
      class: App\Entity\User
